services:
  app:
    image: agoneek/api-weather:0.1.0
    ports:
      - ${PORT}:${PORT}
    environment:
      - API_KEY=${API_KEY}
      - PORT=${PORT}
      - VERSION=${VERSION}
    restart: unless-stopped
