---
- name: Load kernel module br_netfilter and overlay
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - br_netfilter
    - overlay

- name: Ensure kernel modules are loaded at boot
  ansible.builtin.copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      br_netfilter
      overlay
    owner: root
    group: root
    mode: '0644'
