---
- name: Ensure dependencies are installed
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: true
    state: present
  with_items:
    - software-properties-common
    - curl
    - gpg
