---
- name: Install dependencies
  ansible.builtin.import_tasks: dependencies.yml

- name: Ensure directory for GPG-key exists, load and dearmor GPG-key
  ansible.builtin.import_tasks: gpg_key.yml

- name: Add CRI-O repository
  ansible.builtin.import_tasks: CRI-O_repository.yml

- name: Install CRI-O
  ansible.builtin.import_tasks: CRI-O_install.yml

- name: CRI-O service start
  ansible.builtin.import_tasks: CRI-O_start.yml

- name: Ensure CRI-O config exists
  ansible.builtin.import_tasks: CRI-O_config.yml
