---
- name: Enable and start kubelet service
  ansible.builtin.systemd:
    name: kubelet
    enabled: true
    state: started

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
