- name: Ensure containerRuntimeEndpoint is set for Kubelet
  ansible.builtin.lineinfile:
    path: "{{ kubelet_runtime_config_path }}"
    regex: '^containerRuntimeEndpoint:.*'
    line: 'containerRuntimeEndpoint: {{ kubelet_runtime_socket }}'
    state: present
  become: true
  when: "'master' in group_names"
  notify: Restart Kubelet service

- name: Ensure KUBELET_EXTRA_ARGS is set with correct node IP
  ansible.builtin.lineinfile:
    path: "{{ kubelet_config_path }}"
    regexp: '^KUBELET_EXTRA_ARGS='
    line: 'KUBELET_EXTRA_ARGS=--node-ip={{ ansible_default_ipv4.address }}' # ansible_ens3.ipv4.address
    state: present
    create: true
    backup: true
    mode: "0644"
    owner: root
    group: root
  become: true
  notify: Restart Kubelet service

- name: Remove duplicate crio.runtime section if exists
  ansible.builtin.replace:
    path: /etc/crio/crio.conf.d/10-crio.conf
    regexp: '^\[crio\.runtime\](\n.*?)*(?=\n\[|$)'
    replace: ''

- name: Ensure crio.runtime "NET_RAW" is set
  ansible.builtin.blockinfile:
    path: /etc/crio/crio.conf.d/10-crio.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK - CRIO.RUNTIME"
    block: |
      [crio.runtime]
      default_runtime = "crun"
      default_capabilities = [
         "CHOWN",
         "DAC_OVERRIDE",
         "FOWNER",
         "FSETID",
         "SETGID",
         "SETUID",
         "SETPCAP",
         "NET_BIND_SERVICE",
         "NET_RAW"
      ]
  notify: Restart CRI-O service
