---
kube_servers:
  hosts:
    node_1:
      ansible_host: 178.170.242.27
      ansible_port: 2201
      ansible_user: root
    node_2:
      ansible_host: 178.170.242.27
      ansible_port: 2202
      ansible_user: root
    node_3:
      ansible_host: 178.170.242.27
      ansible_port: 2203
      ansible_user: root

  children:
    master:
      hosts:
        node_1:
    worker:
      hosts:
        node_2:
        node_3:
