---
- name: Ensure existance GPG-key
  ansible.builtin.stat:
    path: "{{ k8s_apt_key_gpg_path }}"
  register: k8s_key_stat

- name: Ensure keyrings directory exists
  ansible.builtin.file:
    path: "{{ k8s_keyrings_path }}"
    state: directory
    mode: "0755"

- name: Add k8s project GPG-key
  when: not k8s_key_stat.stat.exists
  block:
    - name: Load GPG-key
      ansible.builtin.get_url:
        url: "{{ k8s_gpg_key }}"
        dest: "{{ k8s_apt_key_asc_path }}"
        mode: "0644"

    - name: Dearmor the GPG key
      ansible.builtin.command:
        cmd: "gpg --dearmor -o {{ k8s_apt_key_gpg_path }} {{ k8s_apt_key_asc_path }}"
        creates: "{{ k8s_apt_key_gpg_path }}"
    - name: Remove the temporary ASCII GPG key
      ansible.builtin.file:
        path: "{{ k8s_apt_key_asc_path }}"
        state: absent
