---
- name: Install k8s utils
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - kubelet
    - kubeadm
    - kubectl


- name: Hold k8s utils to prevent automatic updates
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - kubelet
    - kubeadm
    - kubectl
